# Project: Proyecto2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../../../Downloads/Lista_Simple/Lista_Simple/ListaEnlazada.o ../../../../Downloads/Lista_Simple/Lista_Simple/main.o ../../../../Downloads/Lista_Simple/Lista_Simple/Validar.o
LINKOBJ  = ../../../../Downloads/Lista_Simple/Lista_Simple/ListaEnlazada.o ../../../../Downloads/Lista_Simple/Lista_Simple/main.o ../../../../Downloads/Lista_Simple/Lista_Simple/Validar.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Proyecto2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../../Downloads/Lista_Simple/Lista_Simple/ListaEnlazada.o: ../../../../Downloads/Lista_Simple/Lista_Simple/ListaEnlazada.cpp
	$(CPP) -c ../../../../Downloads/Lista_Simple/Lista_Simple/ListaEnlazada.cpp -o ../../../../Downloads/Lista_Simple/Lista_Simple/ListaEnlazada.o $(CXXFLAGS)

../../../../Downloads/Lista_Simple/Lista_Simple/main.o: ../../../../Downloads/Lista_Simple/Lista_Simple/main.cpp
	$(CPP) -c ../../../../Downloads/Lista_Simple/Lista_Simple/main.cpp -o ../../../../Downloads/Lista_Simple/Lista_Simple/main.o $(CXXFLAGS)

../../../../Downloads/Lista_Simple/Lista_Simple/Validar.o: ../../../../Downloads/Lista_Simple/Lista_Simple/Validar.cpp
	$(CPP) -c ../../../../Downloads/Lista_Simple/Lista_Simple/Validar.cpp -o ../../../../Downloads/Lista_Simple/Lista_Simple/Validar.o $(CXXFLAGS)
